project:
  type: book
  output-dir: docs

book:
  title: "Gavin Rolls - Learning Diary for CASA 0023"
  author: "Gavin Rolls"
  date: "1/18/2024"
  chapters:
    - index.qmd
    - wk1.qmd
    - wk2.qmd
    - wk3.qmd
    - wk4.qmd
    - wk5.qmd
    - wk6.qmd
    - wk7.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual

