---
title: "Advanced Classification and Accuracy Assesment"
author: "Gavin Rolls"
date: "3/12/2024"
---

## Summary

A continuation of last week's look into the classification of remotely sensed imaging, we focused this weekend on a handful of more advanced methods, with a particular focus on determining the accuracy of classifications. I will briefly touch on some of those methods before taking the majority of the summary to talk about accuracy asssement

### Object Based Image Analysis

Object based image analysis is a method of for analysing remotely sensed data at the multi-pixel or 'superpixel' level by identifying discrete physical objects (buildings, small bodies of water, fields, etc...) which can then be classified at object level as opposed to considering pixels in isolation [@blaschke2010]. The most common way of doing this is an algorithm known as Simple Liear Iterative Clustering, which partitions the image into a grid before iteratively moving the centre of each cell to best capture the pixels which are most homogeneous with the rest of the chunk, in a manner similar to k-means clustering [@achanta2012]. This algorithm attempts to keep objects both spatially and spectrally compact, meaning they retain consistent appearance and a small physical distance from end to end.

### Sub-Pixel Analysis

In contrast to analysis at the multi-pixel analysis, sub-pixel analysis concerns the classification of individual pixels when they may fall into multiple land-cover categories. This is particularly important for satellite imagery taken at a low spatial resolution, where individual pixels represent a larger share of land area [@du2014]. A classic method for sub-pixel analysis is multiple endmember spectral mixture analysis, also known as MESMA, which attempts to identify the proportion of each landcover type within each pixel. To do this, each pixel's spectral signature is compared against endmembers (spectral representations of landcover types - often but not always soil, vegetation, and impervious surfaces) to identify the endmembers which most contributed to the pixel's 'mixed signature' [@quintano2013]. This process is known as unmixing - basically breaking a pixel down into its constituent landcover components.

### Accuracy Assessment

The key issue we focused on in lecture (and which I would like to focus on in this review) is that of determining how accurately a landcover classification algorithm has actually divided an image. There are two key accuracy metrics to consider:

1.  **Producer Accuracy**\
    \[TEXT\]
2.  **User's Accuracy\
    **\[Text\]

\[Continue here.\]

## Applications in Research

\[WIP\]

## Reflection

\[WIP\]

## References
